#!/bin/bash


echo "starting jupyter extension installs"
jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager
jupyter labextension install  @bokeh/jupyter_bokeh
jupyter lab build
